name:                Examples
version:             0.1.0.0
github:              "emmettng/Examples"
license:             BSD3
author:              "Wu Hao"
maintainer:          "wuhao@protonmail.com"
copyright:           "Wu Hao"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/emmettng/Examples#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - text
  - Decimal 
  - random
  - mtl
  - containers
  - time
  - vector
  - configurator        ### Package.Configurator
  - statistics
  - transformers
  - store


executables:
  Examples-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Examples

tests:
  Examples-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Examples
